networks:
  share:
    name: share
    driver: bridge

services:
  new-api:
    build: elliottwen/new-api:latest
    networks:
      - share
    container_name: new-api
    restart: always
    ports:
      - "3004:3000"
    volumes:
      - ./data:/data
    environment:
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - STREAMING_TIMEOUT=180
    depends_on:
      - redis
  redis:
    image: redis:latest
    networks:
      - share
    container_name: redis
    restart: always